# Generated by Django 3.1.3 on 2020-12-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=200)),
                ('subcounty', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinyozi', models.IntegerField(default=0)),
                ('chips', models.IntegerField(default=0)),
                ('kiosk', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('art', models.IntegerField(default=0)),
                ('carwash', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
    ]
