# Generated by Django 3.1.3 on 2020-12-16 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cobler',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='cyber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='eggs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='mkokoteni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='mutura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='tea',
            field=models.IntegerField(default=0),
        ),
    ]
